modLoader = "javafml"
loaderVersion = "[${forgeDependencyVersion},)"
license = "MIT"

[[mods]]
modId = "hexiron"
version = "${version}"
displayName = "Hexiron"
logoFile = "icon.png"
authors = "beholderface"
description = '''
A Hex Casting addon that adds interop with Iron's Spells n' Spellbooks
'''

[[dependencies.hexiron]]
modId = "forge"
mandatory = true
versionRange = "[${forgeDependencyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexiron]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexiron]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexiron]]
modId = "hexcasting"
mandatory = true
versionRange = "[${hexcastingVersion},)"
ordering = "NONE"
side = "BOTH"
